- 'http://localhost:8000**'
- 'http://localhost:9000**'
- 'https://dvc.us10.list-manage.com/subscribe/post?u=a08bf93caae4063c4e6a351f6&amp;id=24c0ecc49a'
- '**linkedin.com/company/**'
- url
- 'https://dvc.org/pl/api/event'
